version: '3.9'

services:
  app-graph:
    container_name:  app-graph
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    command: ["/app/ pp-graph"]
